### PR TITLE
Fix extra-deps

### PR DESCRIPTION
**Pull request by tdietert**
This PR points to the commit hashes that include the dependency bounds fixes in the dependencies for this package. 

This PR also refactors `Test.Utils` to use the latest version of `network-transport` and `network-transport-tcp`.

### CODE REVIEW

**Comment by tdietert** [comment]
I'm not sure of the policy on pointing to git commits, but until the packages get into a reproducible build plan, this is kind of the best we can do. 

You will notice the CI failures on the last PR merged that "fixed" these deps; I think this PR will build clean.

**Comment by tdietert** [comment]
Well then... any tips on getting this to pass CI? It builds properly on my machine, and all the tests pass... however, none of the CI builds pass.

**Comment by qnikst** [comment]
@tdietert let me try to fix CI errors on your branch. I'll try to add older ghc support back.

**Comment by qnikst** [comment]
@tdietert I've pushed, it worked locally for me. If it passes CI, I'll bump revision and push that to hackage as well.

**Comment by tdietert** [comment]
woot :tada: 
awesome, thanks!

**Comment by qnikst** [comment]
You welcome! I think I'll not add back older versions unless it will be requested or there is a demand from people using those versions in it's own installations. As that would require a lot of maintenance burden. When 8.6 will out, I'll keep support for 8.4 though.

**Pull request merged**
